# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 196a4aae42a5583bed41073dc4edb3d8fdd4f8a73b78bd811ff98b0a76c34f8f936748e64f5cd5ee2340cbc02672b708221c5d6abcc84dd43d68f482424bfb86

test:
  secret_key_base: 57a6139866de9acbfe80aaaee52c43c61b6aab374174e2717fe24e65704044b0a57cc333c3765dc7982edc8418a99f3937e04eb5a3edef8c49de765d9615b79e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
